services:
  ical-proxy:
    build: .
    container_name: ical-proxy
    restart: unless-stopped
    ports:
      - "44444:44444"
    #If using in the same network as Nextcloud
    networks:
      - nextcloud-aio