services:
  ical-proxy:
    #build: .
    image: ical-proxy:latest
    container_name: ical-proxy
    restart: unless-stopped
    ports:
      - "44444:44444"
    environment:
      - TZ=Europe/Berlin
    #If using in the same network as Nextcloud
    networks:
      - nextcloud-aio